### PR TITLE
jsmobile-menu

### PR DESCRIPTION
**Pull request by BenMKT**
-Added `script.js` file for an interactive mobile menu using `javascript` with slight modifications to `index.html` and `styles.css` files to accommodate interactive effects.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
### Hi TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct GitHub-flow followed :+1: 
- [ ] README file has all relevant headers and looks professional :rocket: 
- [ ] Hamburger functionality works as expected :fireworks: 


## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we fix the responsiveness from `768px` t0 `912px` as we can see in the screenshot below
Screenshot from 2023-04-18 13-39-24
Screenshot from 2023-04-18 13-39-50
Screenshot from 2023-04-18 14-03-37
- [ ] It would be better if we match our mobile menu to the figma design, considering the position of the `X` close icon, text color, margin and background effect as we can see below
Screenshot from 2023-04-18 14-07-20
Screenshot from 2023-04-18 14-07-35



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenMKT** [comment]
-Fixed responsiveness bug as per review feedback and fixed mobile menu design to conform to Figma design.

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
# Status: Required Changes :recycle:
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

almost-there

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

[REQUIRED] - I notice that after you implemented the required changes by the previous reviewer 👍, there is a new modification in your design that we need to fix 🛠👀.

Please let's remove the spaces shown in the picture below 👇as that is not present in the given template.

Since our aim is to ensure that our design matches the template as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). 🛠💪

Your design
image

Figma
image

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenMKT** [comment]
-Fixed responsiveness bug.

**Pull request merged**
